### ISSUE TITLE
Are these examples really deprecated?

### ISSUE THREAD

**Issue by hegde00** [ntustison/ANTsRNet#4]
Hi Nick,

The parent page of this page says, "Deprecated / Please see the ANTsRNet repo." But are the *examples* on this page really deprecated? (For one thing, they seem to run fine.)

**BACKGROUND**
Having had good success (with your help) with ANTsR, I have ANTsRNet (and also ANTsPyANTsPyNet) successfully installed on my computer. I' m now looking for example ANTsRNet scripts.

**Comment by ntustison** [comment]
They might *run* fine but that doesn't mean they're using the latest trained weights (probably not) for the best set of results.  Or, equally likely, the applications were moved to within the ANTsXNet libraries themselves for better support, i.e. "deprecated" also implies we no longer support the examples.

**Comment by hegde00** [comment]
Thank you very much. This is very helpful.

(1) So I surmise that these _desprecated_ examples _might_ be OK for strictly learning purposes. Is that about right?

(2) Are there _non-deprecated_ ANTsRNet examples (R scripts) anywhere else?  

I ask because I'm trying to learn how to actually write such scripts for the human hand project. I haven't been able to find any working scripts at all (except those on https://github.com/ANTsX/ANTsPyNet/wiki/Quick-example and https://github.com/ANTsX/ANTsRNet/wiki/ANTsXNet-cortical-thickness, both of which work in my hands).  

I've read some of the relevant publications (including your 2021 Sci. Reports paper), but it's not the same as tinkering with the actual code.

**Comment by ntustison** [comment]
As opposed to the ANTs/ANTsR/ANTsPy libraries (the functionality of which tends to be applicable to a variety of image processing/analysis applications), the ANTsRNet/ANTsPyNet are highly application-specific.  @stnava and I do quite a bit of work with our neuroimaging collaborators using structural MRI so we have several applications specific for processing T1-weighted brain data (as you probably read in the ANTsX paper).  I have several collaborators who do lung research and so I have several ANTsXNet applications for those images.  I also have a collaborator who does aorta vessel segmentation.  I don't know how useful that is for other people but I just dump it in ANTsXNet because it makes things really efficient.  However, we haven't had the need to develop any applications for hand imaging so they don't exist.  We have an entire set of networks in ANTsXNet which researchers can use to do their own training but our experience has informed us that such researchers are extremely rare.    We're happy to share (for example, [here's](https://github.com/ntustison/Histograms/tree/main/ElBichoTraining the training scripts) for a recent paper I wrote) but given the rarity and difficulty of trying to teach people, we don't really provide hands-on support for that sort of thing.

**Comment by hegde00** [comment]
Thank you very much. I understand. That answers both my questions.
